Added JSON configuration file validation with detailed error message in case the file is invalid (or missing)

diff --git a/.github/workflows/generate_student_version.yml b/.github/workflows/generate_student_version.yml
--- a/.github/workflows/generate_student_version.yml
+++ b/.github/workflows/generate_student_version.yml
@@ -38,67 +38,32 @@ jobs:
 
       - name: Validate configuration JSON
         id: validate-json
-        uses: GrantBirki/json-yaml-validate@v2.2.0
-        continue-on-error: true
+        uses: ammarlakis/action-ajv@master
         with:
-          base_dir: "."
-          files: |
-            ${{ env.CONFIG_PATH }}
-          comment: "true"
-          mode: "warn"
-          use_gitignore: "false"  # Désactive l'utilisation du .gitignore
-          json_schema: |
+          schema: |
             {
               "type": "object",
               "required": ["solution_marker", "placeholder", "generate_zip", "notebooks_dir"],
               "properties": {
-                "solution_marker": {
-                  "type": "object",
-                  "description": "Dictionary of markers identifying solution content"
-                },
-                "placeholder": {
-                  "type": "object", 
-                  "description": "Dictionary of replacement text for removed solutions"
-                },
-                "generate_zip": {
-                  "type": "boolean",
-                  "description": "Boolean enabling ZIP archives generation"
-                },
-                "notebooks_dir": {
-                  "type": "array",
-                  "items": { "type": "string" },
-                  "description": "List of directories to process"
-                },
-                "pre_processing": {
-                  "type": "string",
-                  "description": "Optional pre-processing shell command"
-                },
-                "post_processing": {
-                  "type": "string",
-                  "description": "Optional post-processing shell command"
-                }
-              },
-              "additionalProperties": false
+                "solution_marker": {"type": "object"},
+                "placeholder": {"type": "object"},
+                "generate_zip": {"type": "boolean"},
+                "notebooks_dir": {"type": "array", "items": {"type": "string"}},
+                "pre_processing": {"type": "string"},
+                "post_processing": {"type": "string"}
+              }
             }
-
+          data: ${{ env.CONFIG_PATH }}
+          allErrors: true
+      
       - name: Update GitHub Step Summary on Validation Error
-        if:  steps.validate-json.outcome == 'failure'
-        env:
-          STDOUT: ${{ steps.validate-json.outputs.stdout }}
-          STDERR: ${{ steps.validate-json.outputs.stderr }}
+        if: ${{ steps.validate-json.outputs.valid == 'false' }}
         run: |
-            # Utiliser une logique shell standard pour choisir la sortie non vide
-            error_output="$STDOUT"
-            if [ -z "$error_output" ]; then
-                error_output="$STDERR"
-            fi
-            
-            # Afficher les résultats dans le résumé
-            printf "## Configuration file errors\n\n" >> $GITHUB_STEP_SUMMARY
-            printf '%s\n' "$error_output" >> $GITHUB_STEP_SUMMARY
-            printf "Please fix %s.\n" "$CONFIG_PATH" >> $GITHUB_STEP_SUMMARY
-            exit 1
-        
+          printf "## Configuration file errors\n\n" >> $GITHUB_STEP_SUMMARY
+          printf "%ss\n" "${{ steps.validate-json.outputs.errors }}" >> $GITHUB_STEP_SUMMARY
+          printf "Please fix %s.\n" "$CONFIG_PATH" >> $GITHUB_STEP_SUMMARY
+          exit 1
+
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
